# What is a Python Package?


Python Packages are a way to organize and structure your Python code into reusable components. Think of it like a folder that contains related Python files (modules) that work together to provide certain functionality. Packages help keep your code organized, make it easier to manage and maintain, and allow you to share your code with others. They’re like a toolbox where you can store and organize your tools (functions and classes) for easy access and reuse in different projects.

# How to Create Package in Python?


Creating packages in Python allows you to organize your code into reusable and manageable modules. Here’s a brief overview of how to create packages:-

*Create a Directory: Start by creating a directory (folder) for your package. This directory will serve as the root of your package structure.

*
Add Modules: Within the package directory, you can add Python files (modules) containing your code. Each module should represent a distinct functionality or component of your package

*
Init File: Include an __init__.py file in the package directory. This file can be empty or can contain an initialization code for your package. It signals to Python that the directory should be treated as a packag

*.
Subpackages: You can create sub-packages within your package by adding additional directories containing modules, along with their own __init__.py fil

*s.
Importing: To use modules from your package, import them into your Python scripts using dot notat

on. For example, if you have a module named module1.py inside a package named mypackage, you would import its function like this: from mypackage.module1 import gr

*et.
Distribution: If you want to distribute your package for others to use, you can create a setup.py file using Python’s setuptools library. This file defines metadata about your package and specifies how it should be instaled.


# Here’s a basic code sample demonstrating how to create a simple Python package:
-
Create a directory named mypackag

e-.
Inside mypackage, create two Python files: module1.py and module2.

p-y.
Create an __init__.py file inside mypackage (it can be emp

t-y).
Add some code to the mod

u-les.
Finally, demonstrate how to import and use the modules from the pa


*kage.
mypackage/
│
├── __init__.py
├── module1.py
└── module2.py


In [14]:
def world(name):
    print(Hello,{name})

In [15]:
name = "hello"

# Python Packages for Web frameworks

In this segment, we’ll explore a diverse array of Python frameworks designed to streamline web development. From lightweight and flexible options like Flask and Bottle to comprehensive frameworks like Django and Pyramid, we’ll cover the spectrum of tools available to Python developers. Whether you’re building simple web applications or complex, high-performance APIs, there’s a framework tailored to your needs.

# Flask:-
Flask is a lightweight and flexible web framework for Python. It’s designed to make getting started with web development in Python quick and easy, with a simple and intuitive interface. Flask provides tools and libraries to help you build web applications, APIs, and other web services.


# Django:-
Django is a Python web framework for building web applications quickly and efficiently. It follows the DRY principle and includes features like URL routing, database management, and authentication, making development easier. It’s highly customizable and widely used in web development.


# FastAPI:-
Python FastAPI is a high-performance web framework for building APIs quickly and efficiently. It’s easy to use, based on standard Python-type hints, and offers automatic interactive documentation. FastAPI is designed to be fast, easy to learn, and ideal for building modern web APIs.


# Pyramid:-
Python Pyramid is a lightweight web framework for building web applications in Python. It emphasizes flexibility, allowing developers to choose the components they need while providing powerful features for handling HTTP requests, routing, and templating.


# Tornado:-
Python Tornado is a web framework and asynchronous networking library designed for handling high concurrency with non-blocking I/O operations. It’s ideal for building real-time web applications and APIs due to its efficient event-driven architecture.


# Falcon:-
Python Falcon is a lightweight web framework designed for building high-performance APIs quickly and easily. It focuses on simplicity, speed, and minimalism, making it ideal for creating RESTful APIs with minimal overhead.


# CherryPy:-
CherryPy is a minimalist Python web framework for building web applications. It provides a simple and intuitive interface for handling HTTP requests, allowing developers to focus on their application logic without dealing with the complexities of web server management.


# Bottle:-
Python Bottle is a lightweight web framework for building small web applications in Python with minimal effort and overhead. It’s designed to be simple and easy to use, making it great for prototyping and creating simple APIs or web services.


# python packages for AI

Here, we’ll explore key Python libraries for statistical analysis, including NumPy, Pandas, Matplotlibic, Seaborn.

# PYTHON NumPy:-

Numpy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

*Numpy can also be used as an efficient multi-dimensional container of generic data.


# Arrays in Numpy:-

Array in Numpy is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers. In Numpy, number of dimensions of the array is called rank of the array.A tuple of integers giving the size of the array along each dimension is known as shape of the array. An array class in Numpy is called as ndarray. Elements in Numpy arrays are accessed by using square brackets and can be initialized by using nested Python Lists.



In [20]:
#installation of numpy:-

!pip install numpy

In [21]:
import numpy as np

In [31]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[10,100,1000],[9,8,7]])
c = np.array([22,33,44])
print(a)

[1 2 3]


In [32]:
print(c)

[22 33 44]


In [33]:
# example for dimensions:-

s = np.array([20,30,40,50])
print(s)

[20 30 40 50]


In [37]:
a = np.array([3,4,2])
a

array([3, 4, 2])

In [38]:
w = np.array([6,7,5,3,9])
w

array([6, 7, 5, 3, 9])

In [43]:
x = np.array([[8,6,4],[4,8,2]])           #2dimensions
x

array([[8, 6, 4],
       [4, 8, 2]])

In [47]:
print(x)

[[8 6 4]
 [4 8 2]]


In [44]:
e = np.array([[2,4,1],[45,32,99]])
print(e)

[[ 2  4  1]
 [45 32 99]]


In [45]:
r = np.array([[90,80,70],[33,66,99]])
print(r)

[[90 80 70]
 [33 66 99]]


In [46]:
r

array([[90, 80, 70],
       [33, 66, 99]])

In [54]:
t = np.array([[[1,2,3],[4,5,6],[7,8,9]]])      #3dimension
print(t)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [55]:
f = np.array([[[44,56,89],[233,789,560],[12,13,14]]])
f

array([[[ 44,  56,  89],
        [233, 789, 560],
        [ 12,  13,  14]]])

In [56]:
d = np.array([[[44,6,2],[66,7,908],[90.80,70.56,5.9]]])
print(d)

[[[ 44.     6.     2.  ]
  [ 66.     7.   908.  ]
  [ 90.8   70.56   5.9 ]]]


In [57]:
d

array([[[ 44.  ,   6.  ,   2.  ],
        [ 66.  ,   7.  , 908.  ],
        [ 90.8 ,  70.56,   5.9 ]]])

In [58]:
o = np.array([[[4,5,6],[5,6,7],[78,55,3]]])
print(o)

[[[ 4  5  6]
  [ 5  6  7]
  [78 55  3]]]


In [59]:
o

array([[[ 4,  5,  6],
        [ 5,  6,  7],
        [78, 55,  3]]])

In [64]:
t = np.array([[[23,44,22],[4,7,0],[44,56,98]]])
print(t)

[[[23 44 22]
  [ 4  7  0]
  [44 56 98]]]


In [65]:
t

array([[[23, 44, 22],
        [ 4,  7,  0],
        [44, 56, 98]]])

In [66]:
y = np.array([[[2,8,7],[3,5,9],[1,6,44]]])
print(y)

[[[ 2  8  7]
  [ 3  5  9]
  [ 1  6 44]]]


In [67]:
y

array([[[ 2,  8,  7],
        [ 3,  5,  9],
        [ 1,  6, 44]]])

In [69]:
l = np.array([[[[2,3,4],[7,8,5],[8,4,90],[4,65,44]]]])       #4dimension
print(l)

[[[[ 2  3  4]
   [ 7  8  5]
   [ 8  4 90]
   [ 4 65 44]]]]


In [71]:
j = np.array([[[[56,44,89],[33,89,67],[4,7,6],[55,66,77]]]])
print(j)
j

[[[[56 44 89]
   [33 89 67]
   [ 4  7  6]
   [55 66 77]]]]


array([[[[56, 44, 89],
         [33, 89, 67],
         [ 4,  7,  6],
         [55, 66, 77]]]])

In [73]:
h = np.array([[[[3,4,5],[78,98,67],[45,89,90],[8,0,9]]]])
h
print(h)

[[[[ 3  4  5]
   [78 98 67]
   [45 89 90]
   [ 8  0  9]]]]


In [74]:
q = np.array([[[[1,2,3,4],[5,6,7,8],[12,13,14,15],[78,56,98,90]]]])
q

array([[[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [12, 13, 14, 15],
         [78, 56, 98, 90]]]])

In [75]:
print(q)

[[[[ 1  2  3  4]
   [ 5  6  7  8]
   [12 13 14 15]
   [78 56 98 90]]]]


In [76]:
d = np.array([[[[2,5,8],[45,46,47],[3,4,5],[89,78,56]]]])
print(d)

[[[[ 2  5  8]
   [45 46 47]
   [ 3  4  5]
   [89 78 56]]]]


In [77]:
d

array([[[[ 2,  5,  8],
         [45, 46, 47],
         [ 3,  4,  5],
         [89, 78, 56]]]])

In [79]:
c = np.array([[[[[1,2,3],[4,5,6],[6,4,6],[89,78,68],[7,9,80]]]]])   #5dimension
c

array([[[[[ 1,  2,  3],
          [ 4,  5,  6],
          [ 6,  4,  6],
          [89, 78, 68],
          [ 7,  9, 80]]]]])

In [80]:
v = np.array([[[[[2,3,4],[6,7,8],[34,35,36],[78,66,45],[3,4,5]]]]])
print(v)

[[[[[ 2  3  4]
    [ 6  7  8]
    [34 35 36]
    [78 66 45]
    [ 3  4  5]]]]]


In [82]:
u = np.array([[[[[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16],[17,18,19,20]]]]])
print(u)
u

[[[[[ 1  2  3  4]
    [ 5  6  7  8]
    [ 9 10 11 12]
    [13 14 15 16]
    [17 18 19 20]]]]]


array([[[[[ 1,  2,  3,  4],
          [ 5,  6,  7,  8],
          [ 9, 10, 11, 12],
          [13, 14, 15, 16],
          [17, 18, 19, 20]]]]])

# INITIAL PLACEHOLDER:

In [90]:
#zero's as elements we are using
np.zeros((2,4)) #here 2 is rows, 4 is elements in rows


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [91]:
np.zeros((5,9))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [92]:
np.zeros((3,77))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.

In [96]:
!pip install numpy

In [97]:
import numpy as np

In [107]:
#in arrange start value is starting one, middle value is skip value, end value is n-1 using of show the value

arr = np.arange(1, 10, 2)
print(arr) # Output: [1 3 5 7 9]


[1 3 5 7 9]


In [110]:
a = np.arange(1, 20, 5)
print(a) 

[ 1  6 11 16]


In [113]:
x = np.arange(1, 90, 8)
print(x) 

[ 1  9 17 25 33 41 49 57 65 73 81 89]


In [115]:
s = np.arange(0,1000,90)
s

array([  0,  90, 180, 270, 360, 450, 540, 630, 720, 810, 900, 990])

In [116]:
w = np.arange(90,2000,101)
print(w)

[  90  191  292  393  494  595  696  797  898  999 1100 1201 1302 1403
 1504 1605 1706 1807 1908]


# linespace:
The numpy.linspace() function in Python generates an array of evenly spaced values over a specified interval. It is particularly useful for creating sequences of numbers for plotting or other numerical computations

In [118]:
q = np.linspace(1,10,20)
print(q)

[ 1.          1.47368421  1.94736842  2.42105263  2.89473684  3.36842105
  3.84210526  4.31578947  4.78947368  5.26315789  5.73684211  6.21052632
  6.68421053  7.15789474  7.63157895  8.10526316  8.57894737  9.05263158
  9.52631579 10.        ]


In [120]:
w = np.linspace(10,100,100)
w

array([ 10.        ,  10.90909091,  11.81818182,  12.72727273,
        13.63636364,  14.54545455,  15.45454545,  16.36363636,
        17.27272727,  18.18181818,  19.09090909,  20.        ,
        20.90909091,  21.81818182,  22.72727273,  23.63636364,
        24.54545455,  25.45454545,  26.36363636,  27.27272727,
        28.18181818,  29.09090909,  30.        ,  30.90909091,
        31.81818182,  32.72727273,  33.63636364,  34.54545455,
        35.45454545,  36.36363636,  37.27272727,  38.18181818,
        39.09090909,  40.        ,  40.90909091,  41.81818182,
        42.72727273,  43.63636364,  44.54545455,  45.45454545,
        46.36363636,  47.27272727,  48.18181818,  49.09090909,
        50.        ,  50.90909091,  51.81818182,  52.72727273,
        53.63636364,  54.54545455,  55.45454545,  56.36363636,
        57.27272727,  58.18181818,  59.09090909,  60.        ,
        60.90909091,  61.81818182,  62.72727273,  63.63636364,
        64.54545455,  65.45454545,  66.36363636,  67.27

# full:
here in full has starting value is number of time given value and end value has some number

In [129]:
a = np.full((20),100)
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100])

In [125]:
o = np.full((100),101)
print(o)

[101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101 101
 101 101 101 101 101 101 101 101 101 101]


In [130]:
t = np.full((5),9)
t

array([9, 9, 9, 9, 9])

# ndim:
The ndim attribute in NumPy is used to get the number of dimensions of an array. It returns an integer representing the number of dimensions (axes) of the array


In [132]:
t = np.full((5),9)
print(e.ndim)

2


In [139]:
r = np.full((6),9)
print(r)
print(e.ndim)

[9 9 9 9 9 9]
2


In [142]:
t = np.full((100),10)
print(t)
print(e.ndim)

[10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10 10
 10 10 10 10]
2


In [146]:
e = np.full((5,9,8),10)           #no of dimnesion in given ndim function
print("number of Dimi:",e.ndim)

number of Dimi: 3


In [2]:
!pip install numpy

In [3]:
import numpy as np

In [6]:
x = np.full((1,2,3,4,5),9)
print("number is dimi:",x.ndim)

number is dimi: 5


In [3]:
!pip install numpy

In [4]:
import numpy as np

In [ ]:
t = np.full((10,100,1000,10000),10)
print(t)
print("number is dimi:",t.ndim)

# eye():
Return a 2-D array with ones on the diagonal and zeros elsewhere

In [8]:
r = np.eye(10)    #2x2 matrix in arrays
print(r)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [9]:
w = np.eye(30)
w

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0

# random:
The random module in Python provides various functions to generate random numbers and perform random operations. It is widely used in games, simulations, and other applications requiring random number generation

In [22]:
e = np.random.rand(2,3)
print(e)

[[0.50401647 0.91533973 0.68858386]
 [0.84041137 0.86461089 0.27212741]]


In [24]:
r = np.random.rand(5,4)
r

array([[7.45784096e-01, 7.88953039e-01, 3.47194155e-01, 7.37570786e-01],
       [1.53790399e-01, 2.44922479e-01, 8.09980022e-01, 9.64458590e-01],
       [6.50899102e-01, 3.90503156e-01, 1.35291918e-04, 5.76765189e-01],
       [7.87197755e-01, 4.90154518e-01, 3.65346681e-01, 7.26888094e-01],
       [2.14472987e-01, 3.79498665e-01, 9.95311991e-01, 7.56646281e-01]])

# find shape:
To find the shape of an array in NumPy, you can use the .shape attribute. This attribute returns a tuple representing the dimensions of the array.

In [27]:
w = np.array([[1,2,3,4],[2,3,4,6],[5,6,3,5]])
shape = w.shape
print("Shape of the array:", shape)

Shape of the array: (3, 4)


In [31]:
a = np.array([1,2,3,4,5])
shape = a.shape
print("shape of the array:",shape)

shape of the array: (5,)


# find element:
To find an element in a NumPy array in Python, you can use the numpy.where() function. This function returns the indices of the elements that satisfy a given condition.

In [35]:
a = np.array([[1,2,3,5],[5,2,1,4]])
size = a.size
print(a.size)

8


In [36]:
w = np.array([[1,2,3,4],[2,3,4,6],[5,6,3,5]])
size = w.size
print(w.size)

12


# length of array:
This will give you the size of the first dimension (number of rows for a 2D array).Using are len().


In [39]:
a = np.array([[1,2,3,5],[5,2,1,4]])
len(a)

2

In [40]:
w = np.array([[1,2,3,4],[2,3,4,6],[5,6,3,5]])
len(w)

3

# ACCESS ARRAY ELEMENTS:

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.


In [2]:
import numpy as np

In [3]:
#example 

arr = np.array([1, 2, 3, 4])
print(arr[0])

1


In [4]:
arr = np.array([1, 2, 3, 4])
print(arr[3])

4


In [12]:
a = np.array([[[1,2,3],[1,5,6],[8,7,9]]])
print(arr[2])

3


In [18]:
d = np.array([10,100,10,100,100,10])
print(arr[1]+arr[3])

6


# Access 2-D Arrays:-

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.
Think of 2-D arrays like a table with rows and columns, where the dimension represents the row and the index represents the column.



In [30]:
f = np.array([[4,6,2,3,4],[9,6,1,4,7]])
print(arr[1, 2])

8


In [31]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[0,1])                               #2nd element on 1st row


2


# Access 3-D Arrays:-
To access elements from 3-D arrays we can use comma separated integers representing the dimensions and the index of the element.



In [33]:
arr = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr[0,1,2])

6


# Negative Indexing
Use negative indexing to access an array from the end.



In [34]:
arr = np.array([[1,2,3,4,5], [6,7,8,9,10]])
print(arr[1,-2])

9


# Slicing arrays:
Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1








In [2]:
import numpy as np

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])   #index 1 to index 5 
print(arr[1:5])

[2 3 4 5]


In [6]:
print(arr[2:6])

[3 4 5 6]


In [8]:
#from index 4 to the end

arr = np.array([1, 2, 3, 4, 5, 6, 7])
print(arr[4:])

[5 6 7]


In [10]:
print(arr[:4])   #from the beginning to index 4 (not included)


[1 2 3 4]


In [17]:
#Negative Slicing:  Use the minus operator to refer to an index from the end

arr = np.array([1,2,3,4,5,6,7,8,9])
print(arr[-3:-2])

[7]


In [18]:
print(arr[-4:-1])

[6 7 8]


In [21]:
#Use the step value to determine the step of the slicing.

print(arr[1:5:2])     #Return every other element from index 1 to index 5

[2 4]


In [22]:
print(arr[2:8:1])

[3 4 5 6 7 8]


In [23]:
print(arr[::4])       #from the entire array

[1 5 9]


In [27]:
#From the second element, slice elements from index 1 to index 4 (not included):

arr = np.array([[1,2,3,1,2],[4,3,5,6,7]])
print(arr[1, 1:4])

[3 5 6]


In [29]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])    #From both elements, slice index 1 to index 4not given, this will return a 2-D array
print(arr[0:2, 1:4])

[[2 3 4]
 [7 8 9]]


In [30]:
arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])   #From both elements, return index 2
print(arr[0:2, 2])

[3 8]


# Data Types in NumPy

NumPy, a core library for numerical computing in Python, provides a wide array of numeric data types that are optimized for handling large arrays of data. These data types are more extensive than Python's native data types and are closely aligned with C data types, allowing for seamless and fast integration with C, C++, and Fortran code.

->NumPy's data types include:-

Boolean: numpy.bool_, which stores True or False values.

Integer: numpy.int_, numpy.intc, numpy.intp, and sized variants like numpy.int8, numpy.int16, numpy.int32, and numpy.int64.

Unsigned Integer: numpy.uint, numpy.uintc, numpy.uintp, and sized variants like numpy.uint8, numpy.uint16, numpy.uint32, and numpy.uint64.

Floating Point: numpy.float_, numpy.float16, numpy.float32, numpy.float64, and numpy.longdouble for extended precision.

Complex: numpy.complex_, numpy.complex64, numpy.complex128, and numpy.clongdouble for complex numbers with extended precision.




In [3]:
!pip install numpy

In [4]:
import numpy as np

In [5]:
arr = np.array([9,8,7,6,5])
print(arr.dtype)

int32


In [6]:
arr = np.array([10,10,101],dtype = "i")
print(arr.dtype)

int32


In [7]:
arr = np.array(['kavya','navya','maxii','apple','water'])
print(arr.dtype)

<U5


In [8]:
arr = np.array(['kavya','navya','maxii','apple','water'],dtype = "S")
print(arr.dtype)

|S5


In [9]:
arr = np.array([1, 2, 3, 4], dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [10]:
arr = np.array([1, 2, 3, 4], dtype='b')
print(arr)
print(arr.dtype)

[1 2 3 4]
int8


In [11]:
arr = np.array([1+3j,4+55j,44+5j])
print(arr.dtype)

complex128


In [13]:
arr = np.array([1.1,2.2,3.3,4.4,5.5,6.6],dtype ='f')
arr.dtype

dtype('float32')

# NumPy astype() Method:-
The numpy.astype() method is used to change the data type NumPy array from one data type to another.

# Parameters:


dtype: The data type you want to change into.

order: Controls the memory layout order of the result. Options are ‘C’, ‘F’, ‘A’, ‘K’.

casting: Controls the type of data casting. Options are ‘no’, ‘equiv’, ‘safe’, ‘same_kind’, ‘unsafe’.

subok: If True, then sub-classes will be passed-through, otherwise the returned array will be forced to be a base-class array.

copy: By default, astype() returns a newly allocated array. If set to false, the input array is returned instead of a copy.

Return: The method returns a new array with new data type.

In [14]:
#integer into float

arr = np.array([1,2,3,4,5,6,7])
arr = arr.astype('float') 
print(arr.dtype)

float64


In [15]:
arr = np.array([10, 20, 30, 40, 50]) 
print(arr)
print(arr.dtype)

[10 20 30 40 50]
int32


In [16]:
arr = arr.astype('float') 
print(arr) 
print(arr.dtype)

[10. 20. 30. 40. 50.]
float64


In [17]:
arr = arr.astype('complex')    # integer into complex
print(arr)
print(arr.dtype)

[10.+0.j 20.+0.j 30.+0.j 40.+0.j 50.+0.j]
complex128


In [18]:
arr = arr.astype('bool')         #integer into boolean
print(arr)
print(arr.dtype)

[ True  True  True  True  True]
bool


In [19]:
arr1 = np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7]) 
print(arr1.dtype)

float64


In [20]:
arr1 = arr1.astype('int')  #float into intger
print(arr1.dtype)
print(arr1)

int32
[1 2 3 4 5 6 7]


In [21]:
arr1 = arr1.astype('complex')   #float into complex
print(arr1.dtype)
print(arr1)

complex128
[1.+0.j 2.+0.j 3.+0.j 4.+0.j 5.+0.j 6.+0.j 7.+0.j]


In [22]:
arr1 = arr1.astype('bool')    #float into boolean
print(arr1.dtype)
print(arr1)

bool
[ True  True  True  True  True  True  True]


In [23]:
arr2 = np.array([1+2j,3+8j,1+5j,4+6j,4+55j,9+1j])     #complex array
print(arr2.dtype)

complex128


In [25]:
arr2 = arr2.astype('int')
print(arr2.dtype)
print(arr2)

int32
[1 3 1 4 4 9]


In [26]:
arr2  = arr2.astype('float')
print(arr2.dtype)
print(arr2)

float64
[1. 3. 1. 4. 4. 9.]


In [27]:
arr2 = arr2.astype('bool')
print(arr2.dtype)
print(arr2)

bool
[ True  True  True  True  True  True]


In [28]:
arr3 = np.array([1,0,1,2,0,3,0])  #boolean
print(arr3.dtype)

int32


In [29]:
arr3 = arr3.astype('int')
print(arr3.dtype)
print(arr3)

int32
[1 0 1 2 0 3 0]


In [30]:
arr3 = arr3.astype('float')
print(arr3.dtype)
print(arr3)

float64
[1. 0. 1. 2. 0. 3. 0.]


In [31]:
arr3 = arr3.astype('complex')
print(arr3.dtype)
print(arr3)

complex128
[1.+0.j 0.+0.j 1.+0.j 2.+0.j 0.+0.j 3.+0.j 0.+0.j]


# Copy method:


It is used to create a new array that is a copy of an existing array but does not share memory with it. This means that making any changes to the original array won’t affect the existing array.

Use numpy.copy() function to copy Python NumPy array (ndarray) to another array. This method takes the array you wanted to copy as an argument and returns an array copy of the given object. The copy owns the data and any changes made to the copy will not affect the original array

In [47]:
arr = np.array([1,2,3,2,7,6])
x = arr.copy()
arr[3] = 5
print(x)
print(arr)

[1 2 3 2 7 6]
[1 2 3 5 7 6]


In [48]:
s = np.array([10,100,10,1000,10000])
a = s.copy()
s[2] = 1000
print(s)
print(a)

[   10   100  1000  1000 10000]
[   10   100    10  1000 10000]


# View method:

The view is just a view of the original ndarray and the view does not own the data. 

You can create an array view using the view() function of the NumPy library.

This is also known as Shallow Copy. 

When we make changes to the view it affects the original array, and when changes are made to the original array it affects the view.

In [50]:
arr1 = np.array([1,2,3,4,5,6])
y = arr1.view()
arr1[2] = 9
print(arr1)
print(y)

[1 2 9 4 5 6]
[1 2 9 4 5 6]


In [51]:
q = np.array([10,100,1000,10000,100000])
w = q.view()
q[2] = 1000000
print(q)
print(w)

[     10     100 1000000   10000  100000]
[     10     100 1000000   10000  100000]


# Reshaping array:

Reshaping arrays in NumPy is a common task that allows you to change the shape of an array without altering its data. Here’s a quick guide on how to do it using the reshape function.


Reshaping arrays in NumPy is a common task that allows you to change the shape of an array without altering its data. Here’s a quick guide on how to do it using the reshape function.

In [52]:
arr = np.array([1,2,3,4,5,6,7,8])
print(arr.size)
newarr = arr.reshape(2,4)
print(newarr)

8
[[1 2 3 4]
 [5 6 7 8]]


In [57]:
x = np.array([10,1000,100,101,102,103])
s = x.reshape(2,3)
print(x.size)
print(s)

6
[[  10 1000  100]
 [ 101  102  103]]


# Addition,subtraction,multiply,divide,square,sort Arrays:

In [58]:
a = np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
b = np.array([[[10,9,8,7,6],[5,4,3,2,1],[3,4,2,5,6]]])

In [60]:
print(np.add(a,b))    #addition of two array

[[[11 11 11 11 11]
  [11 11 11 11 11]
  [14 16 15 19 21]]]


In [61]:
print(a-b)       #subtraction of two array

[[[-9 -7 -5 -3 -1]
  [ 1  3  5  7  9]
  [ 8  8 11  9  9]]]


In [62]:
print(a*b)      #multiply of two array

[[[10 18 24 28 30]
  [30 28 24 18 10]
  [33 48 26 70 90]]]


In [63]:
print(np.divide(a,b))      #divide of two array

[[[ 0.1         0.22222222  0.375       0.57142857  0.83333333]
  [ 1.2         1.75        2.66666667  4.5        10.        ]
  [ 3.66666667  3.          6.5         2.8         2.5       ]]]


In [68]:
print(np.sqrt(a))    #square of array

[[[1.         1.41421356 1.73205081 2.         2.23606798]
  [2.44948974 2.64575131 2.82842712 3.         3.16227766]
  [3.31662479 3.46410162 3.60555128 3.74165739 3.87298335]]]


In [69]:
print(np.sqrt(b))

[[[3.16227766 3.         2.82842712 2.64575131 2.44948974]
  [2.23606798 2.         1.73205081 1.41421356 1.        ]
  [1.73205081 2.         1.41421356 2.23606798 2.44948974]]]


# sort array:
The numpy.sort() function sorts the array in ascending order by default. You can also sort arrays along a specific axis or use different sorting algorithms like ‘quicksort’, ‘mergesort’, ‘heapsort’, or 'stable’12.

In [70]:
print(np.sort(a))

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]


In [72]:
print(np.sort(b))

[[[ 6  7  8  9 10]
  [ 1  2  3  4  5]
  [ 2  3  4  5  6]]]


# Slicing Array:

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1



In [73]:
arr = np.array([9,4,5,6,2,5])
print(arr[1:4])

[4 5 6]


In [75]:
print(arr[:5]) #no starting element

[9 4 5 6 2]


In [76]:
print(arr[3:])     #no ending element

[6 2 5]


In [78]:
print(arr[-1:-5])      #negtive array

[]


In [86]:
arr1 = np.array([1,2,3,4,2,4,1,5,7,3,5,6])
print(arr1[0:9:2])                             # first starting, count element,steps next element with n-1

[1 3 2 1 7]


In [89]:
print(arr1[::7])      #return every other element 

[1 5]


In [90]:
s = np.array([[4,5,6,3],[7,4,2,4]])
print(s[1,1:4])

[4 2 4]


In [94]:
arr = np.array([[[2,4,5],[6,7,4],[2,9,5]]])
print(arr[0:2,2])

[[2 9 5]]


In [103]:
print(arr[0:2,1])

[[6 7 4]]
